# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/NextState.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/OutputFunction.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/DFlipFlop.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/WriteRegSelector.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/WriteDataSelector.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/RegisterFile.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/PCSelector.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/PCJump.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/PCBranch.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/PCAddFour.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/PC.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/IR.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/InstructionMemory.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/DBDR.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/DataOutSelector.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/DataMemory.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/BDR.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/ALUoutDR.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/ALU.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/ADR.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/ControlUnit.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/MultiCycleCPU.v
  C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/sources_1/new/Display.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/constrs_1/new/BASY3.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/MultiCycleCPU-basy3version/MultiCycleCPU-basy3version.srcs/constrs_1/new/BASY3.xdc]


synth_design -top Display -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Display.dcp

catch { report_utilization -file Display_utilization_synth.rpt -pb Display_utilization_synth.pb }
