# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/RegisterFile.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/PC.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/InstructionMemory.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/DataMemory.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/ControlUnit.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/ALU.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/MonoCycleCPU.v
  C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/sources_1/new/DisplaySelect.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/constrs_1/new/BASY.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/CPU/basy3-version/MonoCycleCPU/MonoCycleCPU.srcs/constrs_1/new/BASY.xdc]


synth_design -top DisplaySelect -part xc7a35tcpg236-1


write_checkpoint -force -noxdef DisplaySelect.dcp

catch { report_utilization -file DisplaySelect_utilization_synth.rpt -pb DisplaySelect_utilization_synth.pb }
